
(pip._vendor.urllib3.exceptions.PoolErrorê
Ö/Users/test/Documents/ALFORIS FINANCE/06. CRM/V1/crm-backend/temp-venv/lib/python3.12/site-packages/pip/_vendor/urllib3/exceptions.py ("2*Ø
2 (n
l
 (4*
(pip._vendor.urllib3.exceptions.PoolError"
pool"__id*$

__unknown_file (

poolc
a
! (;
%2"__concat*
! ()

%s: %s*
- (1

pool*
3 (:
	
message≈¬
 (<
%3"type.__init__*)

__unknown_file (

	HTTPError*H

__unknown_file (,*
(pip._vendor.urllib3.exceptions.PoolError*"

__unknown_file (

%22__init__*
3*b
3
exceptions.py:8
 (
%1"(pip._vendor.urllib3.exceptions.PoolError"
 (

%1:
 (
pool:
 ($	
messageB,*
(pip._vendor.urllib3.exceptions.PoolErrorH