
<pip._internal.exceptions.InstallationSubprocessError.__str__‹
/Users/test/Documents/ALFORIS FINANCE/06. CRM/V1/crm-backend/temp-venv/lib/python3.12/site-packages/pip/_internal/exceptions.py› ›("2* 
2
œ œ(IŠ
‡

œ œ(*
%1"__id*m

__unknown_file (Q*O6
4pip._internal.exceptions.InstallationSubprocessError"
command_description
}

œ9 œ(G
%2"__id*c

__unknown_file (G*E6
4pip._internal.exceptions.InstallationSubprocessError"
	exit_codek
i

œ œ(I
%3"__concat*

œ œ(*

%1*

œ+ œ(8
 exited with *

œ9 œ(G

%2"

œ œ(I

%3B86
4pip._internal.exceptions.InstallationSubprocessErrorH